
{% set name = "ray" %}
{% set version = "0.2.2" %}
{% set sha256 = "ec2c691e5ae85179305a0a4def65de79b3cf20dd6be39f5894d4ad4b9ca83d47" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - cython >= 0.23
    - libgcc
    - toolchain
    - setuptools
  run:
    - python
    - funcsigs
    - click
    - colorama
    - psutil
    - pytest
    - redis
    - cloudpickle == 0.4.1
    - six >= 1.0.0
    - flatbuffers

test:
  imports:
    - ray

about:
  home: https://github.com/ray-project/ray
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Ray is a flexible, high-performance distributed execution framework.'
  description: |
    Ray is a Python-based distributed execution engine.
    The same code can be run on a single machine to achieve efficient multiprocessing,
    and it can be used on a cluster for large computations.
  doc_url: http://ray.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/ray-project/ray

extra:
  recipe-maintainers:
    - barrachri
